#' Find duplicates by fuzzy match of string similarity between adjacent rows
#'
#' @param df Ordered data frame (i.e., output #1 of [RefDeduR::simi_order_adj()]).
#' @param df_simi A data frame with string similarity results calculated from `df` (i.e., output #2 of [RefDeduR::simi_order_adj()]).
#' @param cutoff_title Cutoff threshold of string similarity for normalized title.
#'
#' Range: \[0, 1\]. Defaults to 0.7. We recommend choosing sensible dataset-aware values according to the similarity distribution plot generated by [RefDeduR::plot_simi_dist()].
#' @param cutoff_abstract Cutoff threshold of string similarity for normalized abstract.
#'
#' Range: \[0, 1\]. Defaults to 0.7. We recommend choosing sensible dataset-aware values according to the similarity distribution plot generated by [RefDeduR::plot_simi_dist()].
#'
#' @return Two data frames. (1) `df` with `"match"` column added; (2) A data frame listing `id` of duplicate pairs.
#' @export
#'
#' @examples
#' \dontrun{
#' c(df, id_dup_pair) %<-% dup_find_fuzzy_adj(df, df_simi, cutoff_title = 0.7, cutoff_abstract = 0.7)
#' }
dup_find_fuzzy_adj <- function(
    df,
    df_simi,
    cutoff_title = 0.7,
    cutoff_abstract = 0.7
){
  # Assign numbers ----
  df$match <- integer(nrow(df))
  df$match[1] <- 1

  for (ii in 1:(nrow(df)-1)) {
    if(((is.na(df_simi$abstract_simi[ii]) & df_simi$title_simi[ii] >= cutoff_title)  |  df_simi$title_simi[ii] >= cutoff_title  |   (!is.na(df_simi$abstract_simi[ii]) & df_simi$abstract_simi[ii] >= cutoff_abstract))) {
      df$match[ii+1] <- df$match[ii]
    } else {
      df$match[ii+1] <- df$match[ii]+1
    }
  }

  # generate id of duplicate pairs ----
  id_dup  <- which(duplicated(df$match))-1   # number of index (i.e., number of sets entering the decision tree)

  id_dup_pair <- as.data.frame(id_dup)
  colnames(id_dup_pair) <- "id_r1"

  id_dup_pair$id_r2 <- id_dup_pair$id_r1 + 1

  rownames(id_dup_pair) <- NULL


  return(list(df, id_dup_pair))
}
